AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Seto Playground

  '
Globals:
  Function:
    Handler: lambda_function.lambda_handler
    Runtime: python3.7
    MemorySize: 256
    Timeout: 600
    Tags:
      Application ID: '1184'
      Environment: d0
Resources:
  StateMachineD0:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: StateMachineD0
      DefinitionUri:
        Bucket: seto-cloudformation-play
        Key: 345ccd73bdd42d238663f07f07e0552e
      DefinitionSubstitutions:
        Step1Arn:
          Fn::GetAtt:
          - Step1D0
          - Arn
        Step2Arn:
          Fn::GetAtt:
          - Step2D0
          - Arn
        Step3Arn:
          Fn::GetAtt:
          - Step3D0
          - Arn
      Tags:
        Application ID: '11845'
        Environment: d0
      Role:
        Fn::GetAtt:
        - StateMachineExecutionRole
        - Arn
  StateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - Fn::Sub: states.${AWS::Region}.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - Fn::Sub:
              - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
              - functionName: Step1D0-d0
            - Fn::Sub:
              - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
              - functionName: Step2D0-d0
            - Fn::Sub:
              - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
              - functionName: Step3D0-d0
          - Effect: Allow
            Action:
            - states:StartExecution
            Resource:
              Fn::Sub:
              - arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${stateMachineName}
              - stateMachineName: StateMachineD0
  Step1D0:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Step1D0-d0
      CodeUri: s3://seto-cloudformation-play/5b50a9ff14303d583295ec0caa22fda7
      Description: Step1D0
      Role:
        Fn::GetAtt:
        - Step1ExecutionRole
        - Arn
  Step1ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Permission to run the function
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: Step1ExecutionRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - Fn::Sub:
              - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
              - functionName: Step1D0-d0
  Step2D0:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Step2D0-d0
      CodeUri: s3://seto-cloudformation-play/368d4a2439a65bc26b15c1413d065a6a
      Description: Step2D0
      Role:
        Fn::GetAtt:
        - Step2ExecutionRole
        - Arn
  Step2ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Permission to run the function
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: Step2ExecutionRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - Fn::Sub:
              - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
              - functionName: Step2D0-d0
  Step3D0:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Step3D0-d0
      CodeUri: s3://seto-cloudformation-play/eb27d6d0b8ee765479aa2afea28a79fc
      Description: Step3D0
      Role:
        Fn::GetAtt:
        - Step3ExecutionRole
        - Arn
  Step3ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Permission to run the function
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: Step3ExecutionRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - Fn::Sub:
              - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
              - functionName: Step3D0-d0
Outputs:
  StateMachineD0:
    Description: PlaygroundStateMachineD0
    Value:
      Ref: StateMachineD0
